### ISSUE TITLE
Android Embedding Issue

### ISSUE THREAD

**Issue by vijayb95** [wu9007/qrcode_scanner#106]
Android embedding is need to be updated for this package. Update the package to provide options to generate barcodes as well

**Comment by wu9007** [comment]
Fixed on `master` (qrscan 0.4.0).

Android now uses `FlutterPlugin` + `ActivityAware` (embedding v2). The old `registerWith` path is gone.

pub.dev still lists **0.3.3**. Until 0.4.0 is published, install from git:

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed. Reopen if a current Flutter 3.10+ app still warns after switching to git `master`.
