### ISSUE TITLE
Not support code128

### ISSUE THREAD

**Issue by scorpioRED** [wu9007/qrcode_scanner#131]
Not support code128

**Comment by BraveEvidence** [comment]
This will help https://www.youtube.com/watch?v=w-n0jUrUtPI&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=10 https://www.youtube.com/watch?v=QpnVENc9dIA&list=PLQhQEGkwKZUqZC2QAp_u4ZAzqpsCCRvmM&index=11

**Comment by wu9007** [comment]
Fixed on `master` (qrscan 0.4.0).

Android ZXing formats now include `CODE_128` (also CODE_39/93, EAN, UPC, ITF, Codabar, Data Matrix, PDF417, Aztec, QR). iOS uses Vision barcode detection.

Install from git until pub.dev ships 0.4.0 (pub still has 0.3.3):

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.
