### ISSUE TITLE
何时支持ios

### ISSUE THREAD

**Issue by hqwlkj** [wu9007/qrcode_scanner#34]

**Comment by wu9007** [comment]
现在支持 iOS。`master` 0.4.0 用 Vision 真扫。pub.dev 还是 0.3.3，请从 git 安装：

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.
