### ISSUE TITLE
 Attribute application

### ISSUE THREAD

**Issue by Ikxyz** [wu9007/qrcode_scanner#36]
```
 Attribute application@icon value=(@mipmap/launcher_icon) from AndroidManifest.xml:19:9-45
 is also present at [:qrscan] AndroidManifest.xml:22:9-43 value=(@mipmap/ic_launcher).

```
after adding the plugin I keep getting this error whenever I run my app...

**Comment by sgehrman** [comment]
same here, this is unusable.

**Comment by geekz-reno** [comment]
yes, same here, any workaround?

**Comment by wu9007** [comment]
@Ikxyz same merger as #32 / #53 / #103 / #112 / #120: host `@mipmap/launcher_icon` vs plugin `@mipmap/ic_launcher`.

0.4.0 plugin `AndroidManifest.xml` is an empty `<application>` plus `SecondActivity` — no `android:icon`. The resource is gone, so the merger should stop.

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.
