### ISSUE TITLE
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.

### ISSUE THREAD

**Issue by Wasi-Zafar** [wu9007/qrcode_scanner#43]
Unable to build release due to following error

Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'. >
 Could not resolve all task dependencies for configuration ':app:releaseCompileClasspath'.    > 
Could not find com.github.leyan95:android-zxingLibrary:0.1.1-PRE.      Required by:          project :app > 
com.shinow.qrscan:qrscan_release:1.0

**Comment by wu9007** [comment]
@Wasi-Zafar release compile failed because `com.shinow.qrscan:qrscan_release:1.0` pulled `com.github.leyan95:android-zxingLibrary:0.1.1-PRE`, which is gone (JitPack / the PRE tag).

0.4.0 does not depend on that artifact. `android/build.gradle` is `com.google.zxing:core:3.5.3` + CameraX 1.4 from Google / Maven Central. No JitPack repo is required.

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.
