### ISSUE TITLE
project is still active?

### ISSUE THREAD

**Issue by pabloyokese** [wu9007/qrcode_scanner#63]
project still active? why the last version is not available in pub.dev, thanks!

**Comment by wu9007** [comment]
Yes. `master` is the 0.4.0 revival: Dart 3, embedding v2, CameraX + ZXing, real iOS Vision scanning.

Boundary (on purpose): one-shot `scan()` / `scanPhoto()` / `scanPath()` / `scanBytes()` / `generateBarCode()`. Not an embedded camera widget — that is [mobile_scanner](https://pub.dev/packages/mobile_scanner). Not a hardware gun — that is [pda_scanner](https://github.com/wu9007/pda_scanner) or a `TextField` (HID).

pub.dev still lists 0.3.3. Use git `master` until 0.4.0 is published:

```yaml
dependencies:
  qrscan:
    git:
      url: https://github.com/wu9007/qrcode_scanner.git
      ref: master
```

Closing as completed.
